"""LLM analyzer — optional post-crawl analysis using an LLM provider."""

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, cast


async def analyze_with_llm(
    data: dict, provider: str, api_key: str, output_dir: str
) -> Path | None:
    """Send extracted lottery stats to an LLM for trend analysis.

    Supports any LiteLLM-compatible provider (OpenAI, Anthropic, Groq, etc.).
    Returns the path to the saved analysis markdown, or None on failure.
    """
    try:
        from litellm import acompletion
    except ImportError:
        print("⚠️  litellm not installed. Skipping LLM analysis.")
        print("   Install with: pip install litellm")
        return None

    print(f"🤖 Analyzing with LLM: {provider}")

    summary_json = json.dumps(data, ensure_ascii=False, indent=2)

    prompt = (
        "You are a Thai lottery statistics analyst. "
        "Analyze the following 36-year lottery statistics data and provide:\n\n"
        "1. **Overview**: Summary of the dataset (total draws, period covered)\n"
        "2. **Hot Numbers**: Numbers that appear most frequently in each category\n"
        "3. **Cold Numbers**: Numbers that appear least frequently\n"
        "4. **Digit Position Patterns**: Notable patterns in digit positions\n"
        "5. **Interesting Observations**: Surprising or noteworthy findings\n"
        "6. **Visualization Suggestions**: Chart types and data groupings\n\n"
        "Respond in Thai language. Use markdown formatting.\n\n"
        f"Data:\n{summary_json}"
    )

    try:
        # Set provider-specific env vars for litellm
        _provider_env = {
            "openai": "OPENAI_API_KEY",
            "anthropic": "ANTHROPIC_API_KEY",
            "groq": "GROQ_API_KEY",
        }
        for key, env_var in _provider_env.items():
            if key in provider:
                os.environ[env_var] = api_key

        response = await acompletion(
            model=provider,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3,
            max_tokens=4000,
            api_key=api_key,
        )

        resp: Any = cast(Any, response)
        analysis_text: str = resp.choices[0].message.content or ""

        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)
        analysis_file = out_path / "lottery_analysis.md"

        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        with open(analysis_file, "w", encoding="utf-8") as f:
            f.write("# Thai Lottery Statistics Analysis\n\n")
            f.write(f"_Generated by {provider} on {timestamp}_\n\n")
            f.write(analysis_text)

        print(f"💾 Analysis saved: {analysis_file}")
        return analysis_file

    except Exception as e:
        print(f"⚠️  LLM analysis failed: {e}")
        return None
