import * as fs from "fs";
import * as path from "path";
import { loadConfig, loadCookies } from "./config";

/**
 * Convert JSON cookies (Playwright/browser export format)
 * to Netscape cookies.txt format for yt-dlp.
 */
function jsonToNetscape(
  cookies: Array<{
    name: string;
    value: string;
    domain: string;
    path: string;
    expires: number;
    httpOnly: boolean;
    secure: boolean;
  }>
): string {
  const lines = ["# Netscape HTTP Cookie File", "# Generated by fb-group-guides-crawler", ""];

  for (const c of cookies) {
    const domain = c.domain.startsWith(".") ? c.domain : `.${c.domain}`;
    const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
    const secure = c.secure ? "TRUE" : "FALSE";
    const expiry = c.expires > 0 ? Math.floor(c.expires) : 0;

    lines.push(
      `${domain}\t${includeSubdomains}\t${c.path}\t${secure}\t${expiry}\t${c.name}\t${c.value}`
    );
  }

  return lines.join("\n") + "\n";
}

function main(): void {
  const config = loadConfig();
  const cookies = loadCookies(config.cookiesPath);

  const outputDir = path.dirname(config.ytdlpCookiesPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const netscapeContent = jsonToNetscape(cookies);
  fs.writeFileSync(config.ytdlpCookiesPath, netscapeContent, "utf-8");

  console.log(`✅ Converted ${cookies.length} cookies to Netscape format`);
  console.log(`   Output: ${config.ytdlpCookiesPath}`);
}

main();
